"""ad image to model

Revision ID: ef239a3e36a1
Revises: c8936f399cbd
Create Date: 2025-11-13 17:55:02.827558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef239a3e36a1'
down_revision: Union[str, Sequence[str], None] = 'c8936f399cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'image_url')
    # ### end Alembic commands ###
