"""favourite foreign key problem

Revision ID: ff2064e58162
Revises: ef239a3e36a1
Create Date: 2025-11-13 21:29:21.667243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2064e58162'
down_revision: Union[str, Sequence[str], None] = 'ef239a3e36a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('favourites_user_id_fkey'), 'favourites', type_='foreignkey')
    op.drop_constraint(op.f('favourites_ad_id_fkey'), 'favourites', type_='foreignkey')
    op.create_foreign_key(None, 'favourites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favourites', 'ads', ['ad_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favourites', type_='foreignkey')
    op.drop_constraint(None, 'favourites', type_='foreignkey')
    op.create_foreign_key(op.f('favourites_ad_id_fkey'), 'favourites', 'ads', ['ad_id'], ['id'])
    op.create_foreign_key(op.f('favourites_user_id_fkey'), 'favourites', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
