"""on delete = cascade chats users

Revision ID: 2fd1bf8e1bc2
Revises: dfa6ac384114
Create Date: 2025-11-27 14:20:17.691115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd1bf8e1bc2'
down_revision: Union[str, Sequence[str], None] = 'dfa6ac384114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chats_seller_id_fkey'), 'chats', type_='foreignkey')
    op.drop_constraint(op.f('chats_buyer_id_fkey'), 'chats', type_='foreignkey')
    op.drop_constraint(op.f('chats_ad_id_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['buyer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chats', 'ads', ['ad_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chats', 'users', ['seller_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_ad_id_fkey'), 'chats', 'ads', ['ad_id'], ['id'])
    op.create_foreign_key(op.f('chats_buyer_id_fkey'), 'chats', 'users', ['buyer_id'], ['id'])
    op.create_foreign_key(op.f('chats_seller_id_fkey'), 'chats', 'users', ['seller_id'], ['id'])
    # ### end Alembic commands ###
