"""correct ad.id

Revision ID: 827a5565b4fc
Revises: 06a49361fc61
Create Date: 2025-11-15 16:17:21.741574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827a5565b4fc'
down_revision: Union[str, Sequence[str], None] = '06a49361fc61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chats_ads_id_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'ads', ['ads_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_ads_id_fkey'), 'chats', 'users', ['ads_id'], ['id'])
    # ### end Alembic commands ###
