"""on delete = cascade ads users

Revision ID: dfa6ac384114
Revises: 74ae4512f465
Create Date: 2025-11-27 14:18:55.695021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa6ac384114'
down_revision: Union[str, Sequence[str], None] = '74ae4512f465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ads_user_id_fkey'), 'ads', type_='foreignkey')
    op.create_foreign_key(None, 'ads', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ads', type_='foreignkey')
    op.create_foreign_key(op.f('ads_user_id_fkey'), 'ads', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
