"""correct ad_id

Revision ID: f707e87d64d6
Revises: 827a5565b4fc
Create Date: 2025-11-20 09:08:16.691302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f707e87d64d6'
down_revision: Union[str, Sequence[str], None] = '827a5565b4fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('ad_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('chats_ads_id_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'ads', ['ad_id'], ['id'])
    op.drop_column('chats', 'ads_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('ads_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_ads_id_fkey'), 'chats', 'ads', ['ads_id'], ['id'])
    op.drop_column('chats', 'ad_id')
    # ### end Alembic commands ###
