"""report model

Revision ID: f73bc855efd8
Revises: 2fd1bf8e1bc2
Create Date: 2025-12-10 21:50:52.715803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73bc855efd8'
down_revision: Union[str, Sequence[str], None] = '2fd1bf8e1bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('reports_reporter_id_fkey'), 'reports', type_='foreignkey')
    op.drop_constraint(op.f('reports_reported_id_fkey'), 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['reporter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reports', 'users', ['reported_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(op.f('reports_reported_id_fkey'), 'reports', 'reports', ['reported_id'], ['id'])
    op.create_foreign_key(op.f('reports_reporter_id_fkey'), 'reports', 'users', ['reporter_id'], ['id'])
    op.alter_column('reports', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
